#!/bin/bash

FILE="$1"
OUTFILE=$(readlink -f -m "$2")

# Check file was given and exists
if [ -z "$OUTFILE" -o -z "$FILE" ]; then
  echo "$0 <prezi_fip_file> <outfile>"
  exit 0
fi;

if [ ! -f "$FILE" -o ! -r "$FILE" ]; then
  echo "Input file missing"
  exit 0
fi;

if [ -z "$OUTFILE" -o -f "$OUTFILE" ]; then
  echo "Output file exists or is not writable!"
  exit 0
fi;

if [ ! `which ruby` ]; then
  echo "You need ruby in your PATH"
  exit 0
fi;

if [ ! `which rackup` ]; then
  echo "You need rack gem installed (gem install rack)"
  exit 0
fi;

# Create temporary working area
TMP=$(tempfile)
rm $TMP
mkdir $TMP

# Copy file to working area and extract
cp $FILE $TMP
cd $TMP
unzip -q *.zip
cd *

# Remove chaff making sure to keep relevant bits
rm prezi.exe
mv prezi.app/Contents/Resources/movie.swf .
rm -rf prezi.app

# Create rackup config
echo "run Rack::Static.new(Rack::File.new(Dir.pwd), :urls => {\"/\" => 'movie.swf'})" > server.ru

# Create bootstrap
echo -n "#!/bin/bash

THIS=\$(readlink -f \"\$0\")
TMP=\$(tempfile -p prezi)
TMP_DIR=\$TMP.dir
BIN_START=\$(grep -an '^PREZI_BIN:' \"\$THIS\" | sed 's/:.*//g')

echo 'Prezi listening on http://localhost:9292/'
echo 'Press CTRL+c to quit'

mkdir \$TMP_DIR
cd \$TMP_DIR && tail -n +\$((BIN_START + 1)) \"\$THIS\" | tar -xf - && rackup server.ru
rm -rf \$TMP_DIR
exit

PREZI_BIN:
" > "$OUTFILE"

# Append binary data
tar -c * >> "$OUTFILE"

chmod +x "$OUTFILE"
